[package]
name = "iterum"
version = "0.1.0"
description = "A utility macro for supporting multiple versions of a struct."
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
iterum_macros = { path = "../iterum_macros", version = "0.1.0" }

[dev-dependencies]
serde.workspace = true
